spring.application.name=mercari-manager
# --- MySQL接続 ---
spring.datasource.url=jdbc:mysql://localhost:3306/mercari_db?useSSL=false&serverTimezone=Asia/Tokyo
spring.datasource.username=root
spring.datasource.password=igunet12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA設定 ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# --- その他 ---
spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true
spring.h2.console.enabled=false

# --- アップロード最大サイズ ---
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
